/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentRequiredRouteImport } from './routes/payment-required'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProtectedFilesRouteImport } from './routes/dashboard/protected-files'
import { Route as DashboardRecipientsRouteImport } from './routes/dashboard/recipients'
import { Route as DashboardTraceRouteImport } from './routes/dashboard/trace'
import { Route as DashboardUploadsRouteImport } from './routes/dashboard/uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRequiredRoute = PaymentRequiredRouteImport.update({
  id: '/payment-required',
  path: '/payment-required',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProtectedFilesRoute = DashboardProtectedFilesRouteImport.update({
  id: '/protected-files',
  path: '/protected-files',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRecipientsRoute = DashboardRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTraceRoute = DashboardTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUploadsRoute = DashboardUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/signup': typeof SignupRoute
  '/dashboard/protected-files': typeof DashboardProtectedFilesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/signup': typeof SignupRoute
  '/dashboard/protected-files': typeof DashboardProtectedFilesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/signup': typeof SignupRoute
  '/dashboard/protected-files': typeof DashboardProtectedFilesRoute
  '/dashboard/recipients': typeof DashboardRecipientsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/payment-required'
    | '/signup'
    | '/dashboard/protected-files'
    | '/dashboard/recipients'
    | '/dashboard/trace'
    | '/dashboard/uploads'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/payment-required'
    | '/signup'
    | '/dashboard/protected-files'
    | '/dashboard/recipients'
    | '/dashboard/trace'
    | '/dashboard/uploads'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/payment-required'
    | '/signup'
    | '/dashboard/protected-files'
    | '/dashboard/recipients'
    | '/dashboard/trace'
    | '/dashboard/uploads'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentRequiredRoute: typeof PaymentRequiredRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-required': {
      id: '/payment-required'
      path: '/payment-required'
      fullPath: '/payment-required'
      preLoaderRoute: typeof PaymentRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/protected-files': {
      id: '/dashboard/protected-files'
      path: '/protected-files'
      fullPath: '/dashboard/protected-files'
      preLoaderRoute: typeof DashboardProtectedFilesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/recipients': {
      id: '/dashboard/recipients'
      path: '/recipients'
      fullPath: '/dashboard/recipients'
      preLoaderRoute: typeof DashboardRecipientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/trace': {
      id: '/dashboard/trace'
      path: '/trace'
      fullPath: '/dashboard/trace'
      preLoaderRoute: typeof DashboardTraceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/uploads': {
      id: '/dashboard/uploads'
      path: '/uploads'
      fullPath: '/dashboard/uploads'
      preLoaderRoute: typeof DashboardUploadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProtectedFilesRoute: typeof DashboardProtectedFilesRoute
  DashboardRecipientsRoute: typeof DashboardRecipientsRoute
  DashboardTraceRoute: typeof DashboardTraceRoute
  DashboardUploadsRoute: typeof DashboardUploadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProtectedFilesRoute: DashboardProtectedFilesRoute,
  DashboardRecipientsRoute: DashboardRecipientsRoute,
  DashboardTraceRoute: DashboardTraceRoute,
  DashboardUploadsRoute: DashboardUploadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentRequiredRoute: PaymentRequiredRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
